server:
  port: 8761

eureka:
  instance:
    hostname: docker-host
  server:
    other-instance: docker-host
    other-port: 8762

turbine:
  app-config: eureka-consumer
  aggregator:
    cluster-config: default
  cluster-name-expression: "'default'"
  instanceUrlSuffix: actuator/hystrix.stream