server:
  port: 8090

spring:
  application:
    name: eureka-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: godigmh
    password: 0123456789
  boot:
    admin:
      client:
        url: http://${eureka.server1.hostname}:${eureka.server1.port}/admin
  devtools:
    restart:
      enabled: false

eureka-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 0
    ConnectTimeout: 3000
    ReadTimeout: 3000
#    指定具体的服务器
#    listOfServers: 120.79.181.160:8080
#ribbon:
#  eureka:
#    enabled: false

mq:
  exchange: fanout.exchange
  queue:
    info:
      name: info.log.queue
      routing:
        key: info.routing.key

    error:
      name: error.log.queue
      routing:
        key: error.routing.key

    all:
      name: all.log.queue
      routing:
        key: all.routing.key


eureka:
  client:
    service-url:
      defaultZone: http://${eureka.server1.hostname}:${eureka.server1.port}/eureka/,http://${eureka.server2.hostname}:${eureka.server2.port}/eureka/

# 暴露监控接点
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

logging:
  level:
    org.ypq.service.ProductService: debug


#feign:
#  httpclient:
#    enable: true
